# Generated by Django 6.0.2 on 2026-03-01 03:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Bet365, Pinnacle, Banca Principal', max_length=100)),
                ('capital_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esporte', models.CharField(choices=[('FUTEBOL', 'Futebol'), ('BASQUETE', 'Basquete'), ('TENIS', 'Tênis'), ('E-SPORTS', 'E-Sports'), ('MMA', 'MMA'), ('VOLEI', 'Vôlei')], default='FUTEBOL', max_length=20)),
                ('competicao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Competição')),
                ('mercado', models.CharField(blank=True, help_text='Ex: Over 2.5, ML', max_length=100, null=True)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('odd', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stake', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Apostado')),
                ('resultado', models.CharField(choices=[('PENDENTE', 'Pendente'), ('GANHA', 'Ganha'), ('PERDIDA', 'Perdida'), ('DEVOLVIDA', 'Devolvida (Void)'), ('CASHOUT', 'Cashout (Encerrada)')], default='PENDENTE', max_length=20)),
                ('valor_cashout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Cashout')),
                ('anotacao', models.TextField(blank=True, null=True)),
                ('banca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apostas', to='bets.banca')),
            ],
        ),
    ]
