# Generated by Django 6.0.2 on 2026-05-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_alter_aposta_id_alter_banca_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aposta',
            options={'ordering': ['-data'], 'verbose_name': 'Aposta', 'verbose_name_plural': 'Apostas'},
        ),
        migrations.AlterModelOptions(
            name='banca',
            options={'ordering': ['nome'], 'verbose_name': 'Banca', 'verbose_name_plural': 'Bancas'},
        ),
        migrations.AlterField(
            model_name='aposta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aposta',
            name='odd',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='banca',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
